network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
  bridges:
    br-ex:
      interfaces: [eth0]
      dhcp4: no
      dhcp6: no
      parameters:
        forward-delay: 0
        stp: false
      addresses: [192.168.0.11/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [1.1.1.1]
