# /etc/netplan/99-openstack.yaml - for 2 interfaces setup
# eth0: management, static IP 192.168.122.85/24 + DNS same as GW
# eth1: provider network, linuxbridge, no IP address by default (reserved 192.168.124.0/24 with gw/dns .1)
---
network:
  version: 2
  ethernets:
    eth0:
      addresses: [192.168.122.85/24]
      gateway4: 192.168.122.1
      nameservers:
        addresses: [192.168.122.1]
    eth1:
      link-local: []
